/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_okcoin_vault_jni_qtum_Qtumj */

#ifndef _Included_com_okcoin_vault_jni_qtum_Qtumj
#define _Included_com_okcoin_vault_jni_qtum_Qtumj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_okcoin_vault_jni_qtum_Qtumj
 * Method:    execute
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_okcoin_vault_jni_qtum_Qtumj_execute
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
