/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_okcoin_vault_jni_xmr_Moneroj */

#ifndef _Included_com_okcoin_vault_jni_xmr_Moneroj
#define _Included_com_okcoin_vault_jni_xmr_Moneroj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_okcoin_vault_jni_xmr_Moneroj
 * Method:    execute
 * Signature: ([Ljava/lang/Object;[Ljava/lang/String;[Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_okcoin_vault_jni_xmr_Moneroj_execute
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     com_okcoin_vault_jni_xmr_Moneroj
 * Method:    transcation
 * Signature: ([Ljava/lang/Object;Ljava/lang/String;[B[Ljava/lang/String;[Ljava/lang/String;)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_okcoin_vault_jni_xmr_Moneroj_transcation
  (JNIEnv *, jobject, jobjectArray, jstring, jbyteArray, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
