/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_okcoin_vault_jni_digibyte_Digibytej */

#ifndef _Included_com_okcoin_vault_jni_digibyte_Digibytej
#define _Included_com_okcoin_vault_jni_digibyte_Digibytej
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_okcoin_vault_jni_digibyte_Digibytej
 * Method:    GetAddressByPrivateKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_okcoin_vault_jni_digibyte_Digibytej_GetAddressByPrivateKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_okcoin_vault_jni_digibyte_Digibytej
 * Method:    SignTranscation
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_okcoin_vault_jni_digibyte_Digibytej_SignTranscation
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
