/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_okcoin_vault_jni_bytom_Bytomj */

#ifndef _Included_com_okcoin_vault_jni_bytom_Bytomj
#define _Included_com_okcoin_vault_jni_bytom_Bytomj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_okcoin_vault_jni_bytom_Bytomj
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_okcoin_vault_jni_bytom_Bytomj_execute
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
